"use strict";
/**
 * Set up database.
 */

const callEach = (arg, ...fns) => fns.forEach(fn => fn(arg));

// Create schema
const createSchema = db => {
  db.prepare(
    `
CREATE TABLE IF NOT EXISTS "tbl_email" (
  "email_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "sent_at"	INTEGER,
  "sent_at_local"	TEXT,
  "email_body"	TEXT
)`,
  ).run();
  db.prepare(
    `
CREATE TABLE IF NOT EXISTS "tbl_report" (
  "report_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "created_at"	INTEGER,
  "body"	TEXT,
  "json"	TEXT
)`,
  ).run();
  db.prepare(
    `
CREATE TABLE IF NOT EXISTS "tbl_record" (
  "record_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "run_id"	INTEGER,
  "domain_id"	INT,
  "record_values"	TEXT,
  "raw"	TEXT,
  FOREIGN KEY("run_id") REFERENCES "tbl_run_datetime"("run_id"),
  FOREIGN KEY("domain_id") REFERENCES "tbl_domain"("domain_id")
)`,
  ).run();
  db.prepare(
    `
CREATE TABLE IF NOT EXISTS "tbl_run_datetime" (
  "run_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "run_datetime"	INT
)`,
  ).run();
  db.prepare(
    `
CREATE TABLE IF NOT EXISTS "tbl_domain" (
  "domain_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "domain_name"	TEXT
)`,
  ).run();
  db.prepare(
    `
CREATE TABLE IF NOT EXISTS "tbl_type" (
  "type_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "type_name"	TEXT
)`,
  ).run();
};

const insertDomainData = db => {
  db.prepare(
    `INSERT INTO "tbl_domain" ("domain_id","domain_name") VALUES 
  (1,'382reporting.ost.dot.gov'),
  (2,'3pdp.fmcsa.dot.gov'),
  (3,'911-test.nhtsa.gov'),
  (4,'911.gov'),
  (5,'ac-1.dot.gov'),
  (6,'ac-2.dot.gov'),
  (7,'ac.dot.gov'),
  (8,'ac1.dot.gov'),
  (9,'ac2.dot.gov'),
  (10,'academy.jccbi.gov'),
  (11,'acbackup.dot.gov'),
  (12,'adfs.dot.gov'),
  (13,'ai.fmcsa.dot.gov'),
  (14,'airconsumer.dot.gov'),
  (15,'aitraining.volpe.dot.gov'),
  (16,'ama310s1.jccbi.gov'),
  (17,'ama310s7.jccbi.gov'),
  (18,'ame.cami.jccbi.gov'),
  (19,'animalreport.ost.dot.gov'),
  (20,'aosftp.jccbi.gov'),
  (21,'api.nhtsa.gov'),
  (22,'app.seavision.volpe.dot.gov'),
  (23,'app.stag.seavision.volpe.dot.gov'),
  (24,'apps.bts.gov'),
  (25,'arc-mcac-a312.jccbi.gov'),
  (26,'arc-mcac-vw117.jccbi.gov'),
  (27,'arc-mcac-vw172.jccbi.gov'),
  (28,'ask.fmcsa.dot.gov'),
  (29,'atcreform.gov'),
  (30,'balancer1.nhtsa.dot.gov'),
  (31,'bip.fhwa.dot.gov'),
  (32,'bomgar.dot.gov'),
  (33,'borderplanning.fhwa.dot.gov'),
  (34,'bts.dot.gov'),
  (35,'c3rs.bts.gov'),
  (36,'ccdp.bts.gov'),
  (37,'cdan-prod-balancer.nhtsa.dot.gov'),
  (38,'cdan.dot.gov'),
  (39,'cdan.nhtsa.gov'),
  (40,'chat.seavision.volpe.dot.gov'),
  (41,'chat.seavision2-integ.volpe.dot.gov'),
  (42,'chat.stag.seavision.volpe.dot.gov'),
  (43,'checkthebox.dot.gov'),
  (44,'civilrights.dot.gov'),
  (45,'closecall.bts.gov'),
  (46,'cms.bts.dot.gov'),
  (47,'cms.data.fra.dot.gov'),
  (48,'cms.dot.gov'),
  (49,'cms.fhwa.dot.gov'),
  (50,'cms.fmcsa.dot.gov'),
  (51,'cms.fta.dot.gov'),
  (52,'cms.marad.dot.gov'),
  (53,'cms.phmsa.dot.gov'),
  (54,'cms.seaway.dot.gov'),
  (55,'cms.secure.dot.gov'),
  (56,'collaboration.fhwa.dot.gov'),
  (57,'corridors.dot.gov'),
  (58,'crashstats.nhtsa.dot.gov'),
  (59,'crashviewer.nhtsa.dot.gov'),
  (60,'crd.dot.gov'),
  (61,'csa.fmcsa.dot.gov'),
  (62,'csatraining.volpe.dot.gov'),
  (63,'cvisn.fmcsa.dot.gov'),
  (64,'damis.dot.gov'),
  (65,'data.fra.dot.gov'),
  (66,'data.transportation.gov'),
  (67,'dataqs.fmcsa.dot.gov'),
  (68,'demo.eebacs.fhwa.dot.gov'),
  (69,'dev.explore.dot.gov'),
  (70,'dialin.dot.gov'),
  (71,'distracteddriving.gov'),
  (72,'distraction.gov'),
  (73,'dot.gov'),
  (74,'dotcms.fra.dot.gov'),
  (75,'dotdmzadf001vg.ext.dot.gov'),
  (76,'dotdmzadf002vg.ext.dot.gov'),
  (77,'dotdmzadf022vg.ext.dot.gov'),
  (78,'dotdmzadf023vg.ext.dot.gov'),
  (79,'dotdmzasr001vg.ext.dot.gov'),
  (80,'dotdmzsus001vg.ext.dot.gov'),
  (81,'dotdmzwas005vg.ext.dot.gov'),
  (82,'dotdmzwas018vg.dot.gov'),
  (83,'dotdmzwas018vg.ext.dot.gov'),
  (84,'dotdmzwas019vg.dot.gov'),
  (85,'dotdmzwas019vg.ext.dot.gov'),
  (86,'dotdmzwws001vg.ext.dot.gov'),
  (87,'dotdr1vdi015vg.dot.gov'),
  (88,'dotdr1vdi016vg.dot.gov'),
  (89,'dotdr1vdi017vg.dot.gov'),
  (90,'dothqevdi015vg.dot.gov'),
  (91,'dothqevdi016vg.dot.gov'),
  (92,'dothqevdi017vg.dot.gov'),
  (93,'dothqnbom001.dot.gov'),
  (94,'dothqnbom002.dot.gov'),
  (95,'dothqnwas053vg.ext.dot.gov'),
  (96,'dotnet.dot.gov'),
  (97,'dp.dot.gov'),
  (98,'drc.dot.gov'),
  (99,'eauth1.fhwa.dot.gov'),
  (100,'edtservice.cdan.dot.gov'),
  (101,'eebacs.fhwa.dot.gov'),
  (102,'einvoice.esc.gov'),
  (103,'eld.fmcsa.dot.gov'),
  (104,'elmscontent.dot.gov'),
  (105,'elmsstaging.dot.gov'),
  (106,'email.dot.gov'),
  (107,'emfie.dot.gov'),
  (108,'ems.gov'),
  (109,'enepa.fhwa.dot.gov'),
  (110,'engage.dot.gov'),
  (111,'environment.fhwa.dot.gov'),
  (112,'epr.marad.dot.gov'),
  (113,'es3.esc.gov'),
  (114,'esc.gov'),
  (115,'escapps.esc.gov'),
  (116,'escsupportservice.esc.gov'),
  (117,'esubmit.rita.dot.gov'),
  (118,'explore.dot.gov'),
  (119,'ezexam.jccbi.gov'),
  (120,'f5ltmvpn-dmz-vip.dot.gov'),
  (121,'faasafety.gov'),
  (122,'faces.fta.dot.gov'),
  (123,'facesdev1.fta.dot.gov'),
  (124,'facesdev2.fta.dot.gov'),
  (125,'facesdev3.fta.dot.gov'),
  (126,'facesdev4.fta.dot.gov'),
  (127,'facesdev5.fta.dot.gov'),
  (128,'facespreprod.fta.dot.gov'),
  (129,'facestest1.fta.dot.gov'),
  (130,'facestest2.fta.dot.gov'),
  (131,'facestest3.fta.dot.gov'),
  (132,'facestest4.fta.dot.gov'),
  (133,'facestest5.fta.dot.gov'),
  (134,'facestraining.fta.dot.gov'),
  (135,'facesuat.fta.dot.gov'),
  (136,'fedstar.phmsa.dot.gov'),
  (137,'fhwa.dot.gov'),
  (138,'fhwaapps.fhwa.dot.gov'),
  (139,'fhwaappssp.fhwa.dot.gov'),
  (140,'fhwaopsweb.fhwa.dot.gov'),
  (141,'filingtarmacdelayplan.dot.gov'),
  (142,'financecommission.dot.gov'),
  (143,'flh.fhwa.dot.gov'),
  (144,'fmcsa.dot.gov'),
  (145,'fmcsa.portal.dot.gov'),
  (146,'forms.cdan.dot.gov'),
  (147,'fra.dot.gov'),
  (148,'fragis.fra.dot.gov'),
  (149,'frahqelpx002ex.ext.dot.gov'),
  (150,'fraipv6.fra.dot.gov'),
  (151,'frasp.fra.dot.gov'),
  (152,'freight.dot.gov'),
  (153,'fta.dot.gov'),
  (154,'ftaecho.fta.dot.gov'),
  (155,'ftaecho2.fta.dot.gov'),
  (156,'ftawebapps.fta.dot.gov'),
  (157,'ftawebprod.fta.dot.gov'),
  (158,'ftp.nhtsa.dot.gov'),
  (159,'geo.dot.gov'),
  (160,'gis.fhwa.dot.gov'),
  (161,'gradedec.fra.dot.gov'),
  (162,'grants.ost.dot.gov'),
  (163,'groups.nhtsa.gov'),
  (164,'gts.nhtsa.gov'),
  (165,'gtstest.nhtsa.gov'),
  (166,'hazmat.fmcsa.dot.gov'),
  (167,'hazmatgrants.phmsa.dot.gov'),
  (168,'hazmatonline.phmsa.dot.gov'),
  (169,'hazmatonlinedevtest.phmsa.dot.gov'),
  (170,'hazmatsafety.dot.gov'),
  (171,'hepgis.fhwa.dot.gov'),
  (172,'hfcc.dot.gov'),
  (173,'highways.dot.gov'),
  (174,'highways.fhwa.dot.gov'),
  (175,'hip.phmsa.dot.gov'),
  (176,'hiptest.phmsa.dot.gov'),
  (177,'hostedsites.volpe.dot.gov'),
  (178,'hovpfs.ops.fhwa.dot.gov'),
  (179,'ia-content-stage.phmsa.dot.gov'),
  (180,'ia-training-stage.phmsa.dot.gov'),
  (181,'icsodiw.nhtsa.gov'),
  (182,'idpwebsealp.fhwa.dot.gov'),
  (183,'info.seavision.volpe.dot.gov'),
  (184,'infobridge.fhwa.dot.gov'),
  (185,'infopave.fhwa.dot.gov'),
  (186,'infosys.fmcsa.dot.gov'),
  (187,'international.fhwa.dot.gov'),
  (188,'its.dot.gov'),
  (189,'jag.cami.jccbi.gov'),
  (190,'keymaster.dot.gov'),
  (191,'learn.dot.gov'),
  (192,'legacy-dredata.nhtsa.gov'),
  (193,'li-public.fmcsa.dot.gov'),
  (194,'mailsync.oig.dot.gov'),
  (195,'map.safercar.gov'),
  (196,'maps.bts.dot.gov'),
  (197,'maps.dot.gov'),
  (198,'marad.dot.gov'),
  (199,'maradpublicsp.marad.dot.gov'),
  (200,'marapps.dot.gov'),
  (201,'maritime.dot.gov'),
  (202,'marweb.marad.dot.gov'),
  (203,'mcmis.volpe.dot.gov'),
  (204,'mcp.nhtsa.gov'),
  (205,'mcs.nhtsa.gov'),
  (206,'mcsac.fmcsa.dot.gov'),
  (207,'mda.volpe.dot.gov'),
  (208,'meet.dot.gov'),
  (209,'mobile.fmcsa.dot.gov'),
  (210,'mos.marad.dot.gov'),
  (211,'mp.dot.gov'),
  (212,'mrb.fmcsa.dot.gov'),
  (213,'mscs.marad.dot.gov'),
  (214,'mssis.volpe.dot.gov'),
  (215,'mutcd.fhwa.dot.gov'),
  (216,'mydomain'),
  (217,'nationalregistry.fmcsa.dot.gov'),
  (218,'nccdb.fmcsa.dot.gov'),
  (219,'near-miss.bts.gov'),
  (220,'nhi.fhwa.dot.gov'),
  (221,'nhthqnwas701.nhtsa.dot.gov'),
  (222,'nhthqnwas733.nhtsa.dot.gov'),
  (223,'nhthqnwas767.nhtsa.dot.gov'),
  (224,'nhthqnwas768.nhtsa.dot.gov'),
  (225,'nhthsaf5b-m.nhtsa.dot.gov'),
  (226,'nhtsa.dot.gov'),
  (227,'nprn.marad.dot.gov'),
  (228,'ntcscheduler.fmcsa.dot.gov'),
  (229,'ntl.bts.gov'),
  (230,'ntlsearch.bts.gov'),
  (231,'oetcrt.dot.gov'),
  (232,'oig.dot.gov'),
  (233,'oigmobile.oig.dot.gov'),
  (234,'one.nhtsa.gov'),
  (235,'ops.fhwa.dot.gov'),
  (236,'opsweb.phmsa.dot.gov'),
  (237,'origin-dr-gts.nhtsa.gov'),
  (238,'origin-www-odi.nhtsa.dot.gov'),
  (239,'origin-www.faasafety.gov'),
  (240,'origin-www.marad.dot.gov'),
  (241,'osdbu.dot.gov'),
  (242,'osthqnwas093.dot.gov'),
  (243,'ostrazedwws001.ext.dot.gov'),
  (244,'ostrazewws001vg.ext.dot.gov'),
  (245,'ostrazewws002vg.ext.dot.gov'),
  (246,'oversight.volpe.dot.gov'),
  (247,'parkingapp.ost.dot.gov'),
  (248,'pdm.phmsa.dot.gov'),
  (249,'phmhqnwas004.phmsa.dot.gov'),
  (250,'phmhqnwas024.phmsa.dot.gov'),
  (251,'phmhqnwas036.phmsa.dot.gov'),
  (252,'phmhqnwas070vg.phmsa.dot.gov'),
  (253,'phmhqnwas071.phmsa.dot.gov'),
  (254,'phmhqnwas071vg.phmsa.dot.gov'),
  (255,'phmhqnwas072vg.phmsa.dot.gov'),
  (256,'phmhqnwas080vg.phmsa.dot.gov'),
  (257,'phmhqnwas102vg.phmsa.dot.gov'),
  (258,'phmsa.dot.gov'),
  (259,'phmsamobile.phmsa.dot.gov'),
  (260,'pipelinesafety.dot.gov'),
  (261,'plan4operations.fhwa.dot.gov'),
  (262,'planning.dot.gov'),
  (263,'pnt.rita.dot.gov'),
  (264,'poolsfc.dot.gov'),
  (265,'portal.dot.gov'),
  (266,'portal.fmcsa.dot.gov'),
  (267,'portal.phmsa.dot.gov'),
  (268,'preprod.faasafety.gov'),
  (269,'primis-stage.phmsa.dot.gov'),
  (270,'primis.phmsa.dot.gov'),
  (271,'protectyourmove.gov'),
  (272,'prs.ost.dot.gov'),
  (273,'pvnpms.phmsa.dot.gov'),
  (274,'railroads.dot.gov'),
  (275,'railroads.fra.dot.gov'),
  (276,'rcapm.fra.dot.gov'),
  (277,'remote.esc.gov'),
  (278,'remote2.esc.gov'),
  (279,'remotef.esc.gov'),
  (280,'reports.cdan.dot.gov'),
  (281,'resourcecenter.911.gov'),
  (282,'rita.dot.gov'),
  (283,'rithqnwws008vg.ext.dot.gov'),
  (284,'rms.dot.gov'),
  (285,'rosap.ntl.bts.gov'),
  (286,'rrsp.fra.dot.gov'),
  (287,'rsac.fra.dot.gov'),
  (288,'rspcb.safety.fhwa.dot.gov'),
  (289,'safecar.gov'),
  (290,'safedigging.dot.gov'),
  (291,'safeocs.gov'),
  (292,'safer.fmcsa.dot.gov'),
  (293,'safercar.gov'),
  (294,'safertruck.gov'),
  (295,'safety.fhwa.dot.gov'),
  (296,'safetydata.fra.dot.gov'),
  (297,'safetytalk.fhwa.dot.gov'),
  (298,'sai.dot.gov'),
  (299,'sas-prod-oa-balancer.nhtsa.dot.gov'),
  (300,'score.fmcsa.dot.gov'),
  (301,'seavision.volpe.dot.gov'),
  (302,'seaway.dot.gov'),
  (303,'secure.dot.gov'),
  (304,'sfm.fmcsa.dot.gov'),
  (305,'sftp.fhwa.dot.gov'),
  (306,'sftp.phmsa.dot.gov'),
  (307,'sharetheroadsafely.gov'),
  (308,'sir.fra.dot.gov'),
  (309,'skynet.nhtsa.gov'),
  (310,'slfts.fhwa.dot.gov'),
  (311,'smarterskies.gov'),
  (312,'sra.volpe.dot.gov'),
  (313,'stag.seavision.volpe.dot.gov'),
  (314,'stage-cidrs.cdan.dot.gov'),
  (315,'stage.fra.dot.gov'),
  (316,'staging.learn.dot.gov'),
  (317,'standards.its.dot.gov'),
  (318,'staqsdevext.esc.gov'),
  (319,'staqspostprodext.esc.gov'),
  (320,'staqsprodext.esc.gov'),
  (321,'staqstestext.esc.gov'),
  (322,'staqstrainext.esc.gov'),
  (323,'statemetrics.nhtsa.gov'),
  (324,'static.nhtsa.gov'),
  (325,'stb.dot.gov'),
  (326,'stbremote.esc.gov'),
  (327,'stg-api.nhtsa.gov'),
  (328,'strap.nhtsa.dot.gov'),
  (329,'strongports.gov'),
  (330,'survey.bts.gov'),
  (331,'swim.volpe.dot.gov'),
  (332,'tankcar.bts.gov'),
  (333,'tdwr.jccbi.gov'),
  (334,'tmcpfs.ops.fhwa.dot.gov'),
  (335,'tmip.fhwa.dot.gov'),
  (336,'trafficsafetymarketing.gov'),
  (337,'training-cidrs.cdan.dot.gov'),
  (338,'training-parse.cdan.dot.gov'),
  (339,'transborder.bts.gov'),
  (340,'transerve.dot.gov'),
  (341,'transit-safety.fta.dot.gov'),
  (342,'transit.dot.gov'),
  (343,'transitapp.ost.dot.gov'),
  (344,'transitapptraining.ost.dot.gov'),
  (345,'transtats.bts.gov'),
  (346,'triprs.nhtsa.dot.gov'),
  (347,'tsi.dot.gov'),
  (348,'tsp.dot.gov'),
  (349,'upa.dot.gov'),
  (350,'usmma.edu'),
  (351,'utc.dot.gov'),
  (352,'vbulletin.phmsa.dot.gov'),
  (353,'vdi-dr.dot.gov'),
  (354,'vdi.dot.gov'),
  (355,'vinrcl.safercar.gov'),
  (356,'voa.marad.dot.gov'),
  (357,'volpe.dot.gov'),
  (358,'volpedb1.volpe.dot.gov'),
  (359,'volpevtc.volpe.dot.gov'),
  (360,'vpic.nhtsa.dot.gov'),
  (361,'vpiclist.cdan.dot.gov'),
  (362,'vpicpubportal.nhtsa.gov'),
  (363,'vrs.volpe.dot.gov'),
  (364,'webapi.nhtsa.gov'),
  (365,'webapps.marad.dot.gov'),
  (366,'webeoc.dot.gov'),
  (367,'websiteaccessibility.dot.gov'),
  (368,'www-esv.nhtsa.dot.gov'),
  (369,'www-fars.nhtsa.dot.gov'),
  (370,'www-nrd.nhtsa.dot.gov'),
  (371,'www-odi.nhtsa.dot.gov'),
  (372,'www.tsi.dot.gov'),
  (373,'www1.oig.dot.gov'),
  (374,'www2.oig.dot.gov'),
  (375,'wxde.fhwa.dot.gov')`,
  ).run();
};

const insertTypeData = db => {
  db.prepare(
    `
INSERT INTO "tbl_type" ("type_id","type_name") VALUES (1,'A'),
  (2,'AAAA'),
  (3,'CNAME'),
  (4,'MX'),
  (5,'NS'),
  (6,'SOA')`,
  ).run();
};

const firstEmail = db => {
  const time = new Date();
  db.prepare(
    `
INSERT INTO "tbl_email" ("sent_at","sent_at_local","email_body")
VALUES (?, ?, "No email - Database initialized")
  `,
  ).run(time.getTime(), time.toLocaleString());
};

const createDatabase = db =>
  callEach(db, createSchema, insertDomainData, insertTypeData, firstEmail);

module.exports = createDatabase;
